version: "3.7"

services:
  apiserver:
    image: thingio/edge-core:latest
    container_name: thingio-apiserver
    command: "./apiserver"
    network_mode: host
    depends_on:
      - datahub
    restart: always

  datahub:
    image: thingio/edge-core:latest
    container_name: thingio-datahub
    command: "./datahub"
    volumes:
      - ./data:/thingio/data
    network_mode: host
    depends_on:
      - mosquitto
    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: thingio-mosquitto
    network_mode: host
    restart: always


