name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:

#  lint:
#    name: Lint
#    runs-on: thingio
#    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v1
#        with:
#          go-version: 1.13.8
#
#      - name: Check out code
#        uses: actions/checkout@v1
#
#      - name: Lint Go Code
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
#          go get -u golang.org/x/lint/golint
#          make lint
#        working-directory: ./apiserver
#
#  test:
#    name: Test
#    runs-on: thingio
#    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v1
#        with:
#          go-version: 1.13.8
#
#      - name: Check out code
#        uses: actions/checkout@v1
#
#      - name: Run Unit tests.
#        run: make test-coverage
#
#      - name: Upload Coverage report to CodeCov
#        uses: codecov/codecov-action@v1.0.0
#        with:
#          token: ${{secrets.CODECOV_TOKEN}}
#          file: ./coverage.txt

  build:
    name: Build
    runs-on: thingio
#    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.8

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: pwd
        working-directory: [./apiserver, bootman]