name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:

  lint:
    name: Lint
    runs-on: thingio
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.8

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint Go Code
        run: bash make_for_each.sh lint

  test:
    name: Test
    runs-on: thingio
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.8

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: bash make_for_each.sh test

      - name: Compute coverage
        run: bash make_for_each.sh coverhtml

  build:
    name: Build
    runs-on: thingio
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.8

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build apiserver
        run: make WORK_DIR=apiserver build

      - name: Build bootman
        run: make WORK_DIR=bootman build

      - name: Build datahub
        run: make WORK_DIR=datahub build

      - name: Build deviceman
        run: make WORK_DIR=deviceman build

      - name: Build funcman
        run: make WORK_DIR=funcman build

      - name: Build pipeman
        run: make WORK_DIR=pipeman build